---

- name: Install Elastic Agent
  command:
    cmd: >
      ./elastic-agent install
      --url={{ fleet_host }}
      --enrollment-token={{ agent_token }}
      --insecure
      --non-interactive
      --force
  args:
    chdir: "/tmp/elastic-agent-{{ stack_version }}-linux-x86_64"
  become: yes