---
- name: Check if Elastic Agent is already installed (Ubuntu)
  stat:
    path: "/opt/Elastic/Agent/elastic-agent"
  register: elastic_agent_binary

- name: Install Elastic Agent (Ubuntu)
  command:
    cmd: >
      ./elastic-agent install
      --url={{ fleet_host }}
      --enrollment-token={{ agent_token }}
      --insecure
      --non-interactive
      --force
  args:
    chdir: "{{ elastic_agent.install_dir }}"
  register: install_result
  when: not elastic_agent_binary.stat.exists

- name: Display installation result (Ubuntu)
  debug:
    var: install_result

- name: Check if installation was successful (Ubuntu)
  fail:
    msg: "Failed to install Elastic Agent"
  when: install_result.rc is defined and install_result.rc != 0

# - name: Clean up
#   file:
#     path: "{{ item }}"
#     state: absent
#   loop:
#     - "{{ elastic_agent.install_dir }}"
#     - "{{ elastic_agent.archive_path }}"

# - name: Elastic Agent setup completed
#   debug:
#     msg: "Elastic Agent setup completed successfully on Ubuntu"
