---
- name: Check if Elastic Agent is installed (Ubuntu)
  shell: elastic-agent version
  register: agent_version_check
  changed_when: false
  failed_when: false

- name: Set installation status
  set_fact:
    elastic_agent_installed: "{{ agent_version_check.rc == 0 }}"

- name: Install Elastic Agent
  command:
    cmd: >
      ./elastic-agent install
      --url={{ fleet_host }}
      --enrollment-token={{ agent_token }}
      --insecure
      --non-interactive
      --force
  args:
    chdir: "{{ elastic_agent.install_dir }}"
  register: install_result
  when: not elastic_agent_installed

- name: Display installation result
  debug:
    var: install_result

- name: Check if installation was successful
  fail:
    msg: "Failed to install Elastic Agent"
  when: not elastic_agent_installed and install_result.rc is defined and install_result.rc != 0
