---
- name: Check if Elastic Agent is already installed
  stat:
    path: "/opt/Elastic/Agent/elastic-agent"
  register: elastic_agent_binary

- name: Install Elastic Agent
  command:
    cmd: >
      ./elastic-agent install
      --url={{ fleet_host }}
      --enrollment-token={{ agent_token }}
      --insecure
      --non-interactive
      --force
  args:
    chdir: "/tmp/elastic-agent-{{ stack_version }}-linux-x86_64"
  register: install_result
  become: yes
  when: not elastic_agent_binary.stat.exists

- name: Display installation result
  debug:
    var: install_result

- name: Check if installation was successful
  fail:
    msg: "Failed to install Elastic Agent"
  when: install_result.rc is defined and install_result.rc != 0

- name: Start Elastic Agent service
  systemd:
    name: elastic-agent
    state: started
    enabled: yes
  become: yes

# - name: Clean up
#   file:
#     path: "{{ item }}"
#     state: absent
#   loop:
#     - "/tmp/elastic-agent-{{ stack_version }}-linux-x86_64"
#     - "/tmp/elastic-agent-{{ stack_version }}-linux-x86_64.tar.gz"
#   become: yes

# - name: Elastic Agent setup completed
#   debug:
#     msg: "Elastic Agent setup completed successfully"