---
- name: Converge
  hosts: all
  tasks:
    - name: Include es-agent role
      include_role:
        name: es-agent
      vars:
        elastic_agent:
          version: "8.15.2"
          fleet_url: "{{ fleet_host }}"
          elasticsearch_host: "{{ es_host }}"
          kibana_host: "{{ kibana_host }}"
          ca_cert: "/elk-stack/certs/ca/ca.crt"
