---
- name: Converge
  hosts: elastic_agents
  tasks:

    - name: Include es-agent role
      include_role:
        name: es-agent
      vars:
        elastic_stack_version: "{{ lookup('env', 'STACK_VERSION') | default('8.15.2', true) }}"
        fleet_host: "{{ lookup('env', 'FLEET_HOST') | default('https://fleet-server:8220', true) }}"
        elasticsearch_host: "{{ lookup('env', 'ELASTICSEARCH_HOST') | default('https://elasticsearch:9200', true) }}"
        elastic_password: "{{ lookup('env', 'ELASTIC_PASSWORD') | default('elastic', true) }}"
        ca_cert: "{{ lookup('env', 'CA_CERT') | default('/usr/share/elasticsearch/config/certs/ca/ca.crt', true) }}"