---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ag-ubuntu
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - name: elastic-stack_elastic-net
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    extra_hosts:
      - "kibana:172.19.0.4"
      - "elasticsearch:172.19.0.3"
      - "fleet-server:172.19.0.2"

  - name: ag-debian
    image: geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - name: elastic-stack_elastic-net
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    extra_hosts:
      - "kibana:172.19.0.4"
      - "elasticsearch:172.19.0.3"
      - "fleet-server:172.19.0.2"

provisioner:
  name: ansible
  env:
    ANSIBLE_REMOTE_TMP: /tmp/.ansible  
    KIBANA_FLEET_HOST: "https://kibana:5601"
    FLEET_HOST: "https://fleet-server:8220"
    ELASTIC_PASSWORD: "${ELASTIC_PASSWORD}"
    KIBANA_PASSWORD: "${KIBANA_PASSWORD}"
    STACK_VERSION: "${STACK_VERSION}"
  inventory:
    group_vars:
      all:
        kibana_fleet_host: "{{ lookup('env', 'KIBANA_FLEET_HOST') }}"
        fleet_host: "{{ lookup('env', 'FLEET_HOST') }}"
        elastic_password: "{{ lookup('env', 'ELASTIC_PASSWORD') }}"
        kibana_password: "{{ lookup('env', 'KIBANA_PASSWORD') }}"
        stack_version: "{{ lookup('env', 'STACK_VERSION') }}"
  playbooks:
    converge: converge.yml      

verifier:
  name: ansible
