---
- name: Verify
  hosts: all
  tasks:
    - name: Check Elastic Agent service status
      service_facts:
      register: services_state

    - name: Verify Elastic Agent service is running
      assert:
        that:
          - "'elastic-agent' in services_state.ansible_facts.services"
          - "services_state.ansible_facts.services['elastic-agent'].state == 'running'"
        fail_msg: "Elastic Agent service is not running"
        success_msg: "Elastic Agent service is running"

    - name: Check agent registration with Fleet
      uri:
        url: "{{ kibana_host }}/api/fleet/agents"
        validate_certs: no
        method: GET
        user: elastic
        password: "{{ elastic_password }}"
        force_basic_auth: yes
        return_content: yes
      register: fleet_agents

    - name: Verify agent is registered
      assert:
        that:
          - "fleet_agents.json.total > 0"
        fail_msg: "No agents registered with Fleet"
        success_msg: "Agent successfully registered with Fleet"
