---
- name: Check if Elastic Agent is installed (Debian)
  shell: "test -f {{ elastic_agent.install_dir }}/elastic-agent && {{ elastic_agent.install_dir }}/elastic-agent version"
  register: agent_version_check
  changed_when: false
  failed_when: false

- name: Set installation status
  set_fact:
    elastic_agent_installed: "{{ agent_version_check.rc == 0 }}"

- name: Check if Elastic Agent is already running
  shell: ps aux | grep -v grep | grep "elastic-agent run"
  register: elastic_agent_process
  changed_when: false
  failed_when: false
  when: not elastic_agent_installed

- name: Run Elastic Agent (without systemd)
  block:
    - name: Run Elastic Agent in background (without systemd)
      shell: >
        cd {{ elastic_agent.install_dir }} && ./elastic-agent run > agent_debug.log 2>&1 &
      async: 45
      poll: 0
      register: elastic_agent_run
      when: elastic_agent_process.rc != 0
  when: not elastic_agent_installed

- name: Enroll Elastic Agent
  command:
    cmd: >
      ./elastic-agent enroll
      --url={{ fleet_host }}
      --enrollment-token={{ agent_token }}
      --insecure
      --v
      --force
  args:
    chdir: "{{ elastic_agent.install_dir }}"
  when: not elastic_agent_installed
