all:
  children:
    elastic_agents:
      hosts:
        agent-ubuntu:
          ansible_connection: community.docker.docker
          ansible_python_interpreter: /usr/bin/python3
          ansible_shell_executable: /bin/bash
          ansible_host: agent-ubuntu
          ansible_remote_tmp: /tmp/.ansible
        agent-debian:
          ansible_connection: community.docker.docker
          ansible_python_interpreter: /usr/bin/python3
          ansible_shell_executable: /bin/bash
          ansible_host: agent-debian
          ansible_remote_tmp: /tmp/.ansible
      vars:
        ansible_user: root