all:
  children:
    elastic_agents:
      hosts:
        agent-ubuntu2-elk-pub:
          ansible_connection: docker
          ansible_python_interpreter: /usr/bin/python3
        agent-debian2-elk-pub:
          ansible_connection: docker
          ansible_python_interpreter: /usr/bin/python3
      vars:
        # Common ELK configuration variables
        kibana_fleet_host: "https://your-public-kibana-host:5601"
        fleet_host: "https://your-public-fleet-host:8220"
        stack_version: "8.15.2"
