all:
  children:
    elastic_agents:
      hosts:
        agent-ubuntu2:
          ansible_connection: docker
          ansible_python_interpreter: /usr/bin/python3
        agent-debian2:
          ansible_connection: docker
          ansible_python_interpreter: /usr/bin/python3
      vars:
        elk_kibana_host: "{{ lookup('env', 'ELK_KIBANA_HOST') }}"
        fleet_host: "{{ lookup('env', 'FLEET_HOST') }}"
        elk_api_key: "{{ lookup('env', 'ELK_API_KEY') }}"
        stack_version: "{{ lookup('env', 'STACK_VERSION') }}"
