---
- name: Prepare containers
  hosts: elastic_agents
  gather_facts: false
  tasks:
    - name: Install Python3
      raw: which python3 || (apt-get update && apt-get install -y python3)
      changed_when: false

    - name: Install required packages
      raw: apt-get install -y curl apt-transport-https gnupg
      changed_when: false

- name: Verify connectivity to ELK stack
  hosts: elastic_agents
  gather_facts: false
  tasks:
    - name: Check Kibana connectivity
      uri:
        url: "{{ kibana_fleet_host }}/api/status"
        method: GET
        validate_certs: no
        headers:
          Authorization: "ApiKey {{ api_key }}"
      register: kibana_status
      ignore_errors: yes

    - name: Fail if Kibana is not reachable
      fail:
        msg: "Unable to connect to Kibana at {{ kibana_fleet_host }}. Please check the URL and ensure Kibana is running and accessible."
      when: kibana_status is failed

- name: Install Elastic Agent
  hosts: elastic_agents
  vars:
    ansible_remote_tmp: /tmp/.ansible
  roles:
    - es-agent
